spring:
  profiles:
    include:
      - stream
    active: dev
  cloud:
    stream:
      binders:
        demoKafka:
          type: kafka
          environment:
            spring.cloud.stream:
              kafka:
                binder:
                  brokers: localhost:9092
                  zkNodes: localhost:2181
                  autoCreateTopics: true
